// Copyright 2026 KeyRack Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file is part of KeyRack.
//
// KeyRack is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// KeyRack is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
// more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with KeyRack. If not, see <https://www.gnu.org/licenses/>.
//
// Alternative commercial licensing is available; contact the Licensor.

//! Key record, key version record, and state machine.
//!
//! The state machine matches `KEYRACK_SPEC.md` §5.4:
//!
//! ```text
//! creating ──► enabled ◄──► disabled
//!                 │              │
//!                 ▼              ▼
//!           pending_deletion ◄───┘
//!                 │
//!                 ▼
//!            destroyed
//! ```
//!
//! Two distinct version concepts exist:
//!
//! - **`occ_version`**: monotonic storage counter for optimistic
//!   concurrency control (§9.2). Bumped on every mutation.
//! - **Key version** (`KeyVersionRecord`): per-rotation material.
//!   Rotation creates a new version; old versions are retained for
//!   decrypt. `current_key_version` identifies the active version
//!   for encrypt/sign operations.

use crate::canon::CanonicalizationVersion;
use crate::lid::Lid;
use crate::provider::KeyHandle;
use crate::tags::{IdentityTags, UserTags};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Key lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KeyState {
    Creating,
    Enabled,
    Disabled,
    /// NIST SP 800-57: key material may have been exposed.
    /// Decrypt/verify allowed for existing data; encrypt/sign forbidden.
    Compromised,
    PendingDeletion,
    Destroyed,
}

impl KeyState {
    /// Whether encrypt and sign operations are permitted.
    #[must_use]
    pub fn permits_encrypt(&self) -> bool {
        matches!(self, Self::Enabled)
    }

    /// Whether decrypt and verify operations are permitted.
    /// Disabled keys allow decrypt for data recovery.
    #[must_use]
    pub fn permits_decrypt(&self) -> bool {
        matches!(self, Self::Enabled | Self::Disabled | Self::Compromised)
    }

    /// Returns the set of states this state can transition to.
    #[must_use]
    pub fn valid_transitions(&self) -> &'static [KeyState] {
        match self {
            Self::Creating => &[Self::Enabled],
            Self::Enabled => &[Self::Disabled, Self::Compromised, Self::PendingDeletion],
            Self::Disabled => &[Self::Enabled, Self::Compromised, Self::PendingDeletion],
            Self::Compromised => &[Self::PendingDeletion],
            Self::PendingDeletion => &[Self::Disabled, Self::Destroyed],
            Self::Destroyed => &[],
        }
    }

    /// Check whether transitioning to `target` is valid.
    #[must_use]
    pub fn can_transition_to(&self, target: Self) -> bool {
        self.valid_transitions().contains(&target)
    }
}

impl std::fmt::Display for KeyState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Creating => f.write_str("creating"),
            Self::Enabled => f.write_str("enabled"),
            Self::Disabled => f.write_str("disabled"),
            Self::Compromised => f.write_str("compromised"),
            Self::PendingDeletion => f.write_str("pending_deletion"),
            Self::Destroyed => f.write_str("destroyed"),
        }
    }
}

/// What the key is used for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum KeyUsage {
    EncryptDecrypt,
    SignVerify,
}

/// Cryptographic algorithm / key spec.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum KeySpec {
    Aes256,
    Ed25519,
    RsaPkcs1v15Sha256 { key_size: u32 },
    RsaPssSha256 { key_size: u32 },
    EcdsaP256Sha256,
}

/// Which provider class backs this key's material.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderClass {
    Software,
    Pkcs11,
    Kmip,
    InMemory,
    VaultTransit,
}

/// Where the key material originated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KeyOrigin {
    /// Generated by `KeyRack` internally.
    KeyRack,
    /// Imported by the operator/tenant.
    External,
}

/// Per-rotation key version record.
///
/// Each rotation creates a new `KeyVersionRecord` with fresh material.
/// Old versions are retained for decrypt/verify of existing ciphertext.
/// The `KeyRecord.current_key_version` field points to the active
/// version for encrypt/sign.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyVersionRecord {
    /// Sequential version number (1, 2, 3, ...).
    pub version_number: u64,
    /// Provider-side handle to the material for this version.
    pub key_handle: KeyHandle,
    /// When this version was created (initial creation or rotation).
    pub created_at: DateTime<Utc>,
    /// Whether this version is the current primary for encrypt/sign.
    pub is_primary: bool,
}

/// The primary key record. Stored in the storage backend.
///
/// `parent_lid` is stored, not recomputed — existing keys preserve their
/// parent relationships even when rules change (see `MIGRATION.md`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyRecord {
    pub lid: Lid,
    pub canonicalization_version: CanonicalizationVersion,
    pub parent_lid: Option<Lid>,

    /// Optimistic concurrency control counter. Bumped on every mutation
    /// (state change, tag update, rotation, metadata edit). Storage
    /// backends check `WHERE occ_version = $expected` and reject on
    /// mismatch (§9.2).
    pub occ_version: u64,

    /// Current primary key version number (for encrypt/sign). References
    /// the `version_number` of one of the entries in `key_versions`.
    pub current_key_version: u64,

    pub state: KeyState,
    pub key_usage: KeyUsage,
    pub key_spec: KeySpec,
    pub origin: KeyOrigin,
    pub provider_class: ProviderClass,
    pub identity_tags: IdentityTags,
    pub user_tags: UserTags,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub scheduled_deletion_at: Option<DateTime<Utc>>,
    pub description: String,

    /// All key versions (rotation history). Version 1 is the original.
    pub key_versions: Vec<KeyVersionRecord>,
}

impl KeyRecord {
    /// Attempt a state transition. Returns `Err` if the transition is invalid.
    pub fn transition_to(
        &mut self,
        target: KeyState,
    ) -> std::result::Result<KeyState, (KeyState, KeyState)> {
        let from = self.state;
        if from.can_transition_to(target) {
            self.state = target;
            self.occ_version += 1;
            self.updated_at = Utc::now();
            Ok(target)
        } else {
            Err((from, target))
        }
    }

    /// Get the primary key version record (for encrypt/sign).
    #[must_use]
    pub fn primary_version(&self) -> Option<&KeyVersionRecord> {
        self.key_versions
            .iter()
            .find(|v| v.version_number == self.current_key_version)
    }

    /// Get a specific key version by number (for decrypt/verify of
    /// ciphertext encrypted with an older version).
    #[must_use]
    pub fn get_version(&self, version_number: u64) -> Option<&KeyVersionRecord> {
        self.key_versions
            .iter()
            .find(|v| v.version_number == version_number)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn creating_can_only_go_to_enabled() {
        assert!(KeyState::Creating.can_transition_to(KeyState::Enabled));
        assert!(!KeyState::Creating.can_transition_to(KeyState::Disabled));
        assert!(!KeyState::Creating.can_transition_to(KeyState::PendingDeletion));
        assert!(!KeyState::Creating.can_transition_to(KeyState::Destroyed));
    }

    #[test]
    fn enabled_transitions() {
        assert!(KeyState::Enabled.can_transition_to(KeyState::Disabled));
        assert!(KeyState::Enabled.can_transition_to(KeyState::PendingDeletion));
        assert!(!KeyState::Enabled.can_transition_to(KeyState::Creating));
        assert!(!KeyState::Enabled.can_transition_to(KeyState::Destroyed));
    }

    #[test]
    fn disabled_transitions() {
        assert!(KeyState::Disabled.can_transition_to(KeyState::Enabled));
        assert!(KeyState::Disabled.can_transition_to(KeyState::PendingDeletion));
        assert!(!KeyState::Disabled.can_transition_to(KeyState::Creating));
        assert!(!KeyState::Disabled.can_transition_to(KeyState::Destroyed));
    }

    #[test]
    fn pending_deletion_transitions() {
        assert!(KeyState::PendingDeletion.can_transition_to(KeyState::Disabled));
        assert!(KeyState::PendingDeletion.can_transition_to(KeyState::Destroyed));
        assert!(!KeyState::PendingDeletion.can_transition_to(KeyState::Enabled));
        assert!(!KeyState::PendingDeletion.can_transition_to(KeyState::Creating));
    }

    #[test]
    fn destroyed_is_terminal() {
        assert!(KeyState::Destroyed.valid_transitions().is_empty());
    }

    #[test]
    fn encrypt_permissions() {
        assert!(!KeyState::Creating.permits_encrypt());
        assert!(KeyState::Enabled.permits_encrypt());
        assert!(!KeyState::Disabled.permits_encrypt());
        assert!(!KeyState::PendingDeletion.permits_encrypt());
        assert!(!KeyState::Destroyed.permits_encrypt());
    }

    #[test]
    fn decrypt_permissions() {
        assert!(!KeyState::Creating.permits_decrypt());
        assert!(KeyState::Enabled.permits_decrypt());
        assert!(KeyState::Disabled.permits_decrypt());
        assert!(!KeyState::PendingDeletion.permits_decrypt());
        assert!(!KeyState::Destroyed.permits_decrypt());
    }

    #[test]
    fn key_record_transition() {
        let mut record = make_test_record(KeyState::Enabled);
        let v = record.occ_version;
        assert!(record.transition_to(KeyState::Disabled).is_ok());
        assert_eq!(record.state, KeyState::Disabled);
        assert_eq!(record.occ_version, v + 1);
    }

    #[test]
    fn key_record_invalid_transition() {
        let mut record = make_test_record(KeyState::Enabled);
        let result = record.transition_to(KeyState::Destroyed);
        assert!(result.is_err());
        assert_eq!(record.state, KeyState::Enabled);
    }

    #[test]
    fn cancel_deletion_returns_to_disabled() {
        let mut record = make_test_record(KeyState::PendingDeletion);
        assert!(record.transition_to(KeyState::Disabled).is_ok());
        assert_eq!(record.state, KeyState::Disabled);
        assert!(record.transition_to(KeyState::Enabled).is_ok());
    }

    #[test]
    fn serde_round_trip_key_state() {
        for state in &[
            KeyState::Creating,
            KeyState::Enabled,
            KeyState::Disabled,
            KeyState::PendingDeletion,
            KeyState::Destroyed,
        ] {
            let json = serde_json::to_string(state).unwrap();
            let parsed: KeyState = serde_json::from_str(&json).unwrap();
            assert_eq!(*state, parsed);
        }
    }

    #[test]
    fn primary_version_lookup() {
        let record = make_test_record(KeyState::Enabled);
        let pv = record.primary_version().unwrap();
        assert_eq!(pv.version_number, 1);
        assert!(pv.is_primary);
    }

    #[test]
    fn get_version_lookup() {
        let record = make_test_record(KeyState::Enabled);
        assert!(record.get_version(1).is_some());
        assert!(record.get_version(999).is_none());
    }

    pub(crate) fn make_test_record(state: KeyState) -> KeyRecord {
        use crate::attr::{AttributeSet, AttributeValue};
        use crate::canon::{canonicalize, CanonicalizationVersion};

        let mut attrs = AttributeSet::new();
        attrs.insert("tenant", AttributeValue::String("test".into()));
        let form = canonicalize(CanonicalizationVersion::V1, &attrs);
        let lid = Lid::derive(CanonicalizationVersion::V1, &form);

        KeyRecord {
            lid,
            canonicalization_version: CanonicalizationVersion::V1,
            parent_lid: None,
            occ_version: 1,
            current_key_version: 1,
            state,
            key_usage: KeyUsage::EncryptDecrypt,
            key_spec: KeySpec::Aes256,
            origin: KeyOrigin::KeyRack,
            provider_class: ProviderClass::Software,
            identity_tags: IdentityTags::from_attribute_set(&attrs),
            user_tags: UserTags::new(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            scheduled_deletion_at: None,
            description: String::new(),
            key_versions: vec![KeyVersionRecord {
                version_number: 1,
                key_handle: KeyHandle {
                    key_id: "test-handle".into(),
                    key_spec: KeySpec::Aes256,
                },
                created_at: Utc::now(),
                is_primary: true,
            }],
        }
    }
}
